version: "3.4"  # 3.4 is minimal version that supports extension-fields
# x-extension fields
x-database_env_file: &env_var
  env_file:
    - ./.env

volumes:
  travel-database:
    name:
      travel-database

services:
  travel_backend:
    <<: *env_var
    container_name: travel_backend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app/
    depends_on:
      - mysql_database
    ports:
      - 8000:8000
    command: bash app/start.sh

  mysql_database:
    <<: *env_var
    container_name: mysql_database
    image: "mysql:8"
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - travel-database:/var/lib/db/data/
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password --mysqlx=0
